import type { Metadata } from "next";
import { site } from "@/lib/content";

export const siteUrl =
  process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || `https://${site.domain}`;

export function absoluteUrl(path = "/"): string {
  if (!path || path === "/") return siteUrl;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `${siteUrl}${normalized}`;
}

/** Default share image generated by app/(frontend)/opengraph-image.tsx */
export const defaultOgImage = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: `${site.name} — ${site.tagline}`,
} as const;

export const defaultKeywords = site.keywords;

type PageMetaInput = {
  title: string;
  description: string;
  path?: string;
  noIndex?: boolean;
  keywords?: string[];
  /** Use absolute title (skip layout template). Homepage should set this. */
  absolute?: boolean;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  images?: { url: string; width?: number; height?: number; alt?: string }[];
};

/** Build consistent title, canonical, keywords, Open Graph and Twitter metadata. */
export function pageMetadata({
  title,
  description,
  path = "/",
  noIndex = false,
  keywords = defaultKeywords,
  absolute = false,
  type = "website",
  publishedTime,
  modifiedTime,
  authors,
  images,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = title.includes(site.name) ? title : `${title} — ${site.name}`;
  const ogImages = images?.length ? images : [defaultOgImage];

  return {
    title: absolute ? { absolute: fullTitle } : title,
    description,
    keywords,
    authors: authors?.map((name) => ({ name })),
    creator: site.name,
    publisher: site.legalName,
    category: "technology",
    alternates: {
      canonical: url,
      types: {
        "application/rss+xml": absoluteUrl("/feed.xml"),
      },
    },
    ...(noIndex
      ? { robots: { index: false, follow: false, nocache: true } }
      : {
          robots: {
            index: true,
            follow: true,
            googleBot: {
              index: true,
              follow: true,
              "max-image-preview": "large" as const,
              "max-snippet": -1,
              "max-video-preview": -1,
            },
          },
        }),
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: site.name,
      locale: "en_US",
      type,
      images: ogImages.map((img) => ({
        url: img.url,
        width: img.width ?? 1200,
        height: img.height ?? 630,
        alt: img.alt ?? fullTitle,
      })),
      ...(type === "article"
        ? {
            publishedTime,
            modifiedTime: modifiedTime ?? publishedTime,
            authors,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: ogImages.map((img) => img.url),
      creator: site.social?.twitterHandle || undefined,
    },
  };
}

export function thumbClass(index: number): string {
  const thumbs = ["thumb--a", "thumb--b", "thumb--c"] as const;
  return thumbs[index % thumbs.length];
}

/** Serialize JSON-LD safely for <script type="application/ld+json"> */
export function jsonLdScript(data: Record<string, unknown> | Record<string, unknown>[]) {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}
